/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string>

export interface Account {
	accessToken: string | null
	accessTokenExpiresAt: Timestamp | null
	accountId: string
	createdAt: Generated<Timestamp>
	id: string
	idToken: string | null
	password: string | null
	providerId: string
	refreshToken: string | null
	refreshTokenExpiresAt: Timestamp | null
	scope: string | null
	updatedAt: Timestamp
	userId: string
}

export interface ChartOfAccounts {
	code: string
	created_at: Generated<Timestamp>
	deleted_at: Timestamp | null
	id: Generated<number>
	name: string
	type: string
	updated_at: Generated<Timestamp>
}

export interface Invites {
	accepted_at: Timestamp | null
	created_at: Generated<Timestamp>
	email: string
	id: Generated<number>
	invited_by_id: string | null
	role: string | null
	status: Generated<string>
	updated_at: Generated<Timestamp>
}

export interface Jwks {
	createdAt: Timestamp
	expiresAt: Timestamp | null
	id: string
	privateKey: string
	publicKey: string
}

export interface Session {
	createdAt: Generated<Timestamp>
	expiresAt: Timestamp
	id: string
	impersonatedBy: string | null
	ipAddress: string | null
	token: string
	updatedAt: Timestamp
	userAgent: string | null
	userId: string
}

export interface TransactionCategories {
	book_type: string
	created_at: Generated<Timestamp>
	default_credit_account_id: number | null
	default_debit_account_id: number | null
	deleted_at: Timestamp | null
	id: Generated<number>
	name: string
	updated_at: Generated<Timestamp>
}

export interface Transactions {
	amount: number
	book_type: string
	category_id: number | null
	created_at: Generated<Timestamp>
	credit_account_id: number
	debit_account_id: number
	description: string | null
	gl_id: number | null
	gl_posting_month: string | null
	id: Generated<number>
	recorded_at: Timestamp | null
	reference_number: string | null
	transaction_date: Timestamp | null
	transferred_to_gl_at: Timestamp | null
	user_id: string
	vat_type: string | null
}

export interface User {
	banExpires: Timestamp | null
	banned: boolean | null
	banReason: string | null
	createdAt: Generated<Timestamp>
	email: string
	emailVerified: boolean
	firstName: string
	id: string
	image: string | null
	lastName: string
	name: string
	role: string | null
	updatedAt: Generated<Timestamp>
}

export interface UserPreferences {
	created_at: Generated<Timestamp>
	id: Generated<number>
	navigation_layout: Generated<string>
	theme: Generated<string>
	updated_at: Generated<Timestamp>
	user_id: string
}

export interface Verification {
	createdAt: Generated<Timestamp>
	expiresAt: Timestamp
	id: string
	identifier: string
	updatedAt: Generated<Timestamp>
	value: string
}

export interface TaxProfiles {
	atc: string
	books_type: string | null
	branch_code: string
	created_at: Generated<Timestamp>
	eight_pct_year: number | null
	has_employees: boolean
	is_8pct_current_year: boolean
	is_vat: boolean
	line_of_business: string | null
	psic: string | null
	rdo_code: string
	registered_address: string
	registered_name: string
	registration_date: string
	taxpayer_type: string
	tin: string
	tin_issuance_date: string | null
	trade_name: string | null
	updated_at: Generated<Timestamp>
	user_id: string
	zip: string | null
}

export interface TaxObligations {
	created_at: Generated<Timestamp>
	end_date: string | null
	form_type: string
	frequency: string
	id: Generated<number>
	is_active: Generated<boolean>
	start_date: string
	tax_type: string
	user_id: string
}

export interface CorDocuments {
	created_at: Generated<Timestamp>
	id: Generated<number>
	mime: string
	ocn: string | null
	original_filename: string | null
	r2_key_display: string | null
	r2_key_json: string | null
	r2_key_original: string
	size_bytes: number
	status: Generated<string>
	tax_year: number | null
	user_id: string
}

export interface TaxFilings {
	computed: unknown | null
	created_at: Generated<Timestamp>
	filed_at: Timestamp | null
	form_type: string
	id: Generated<number>
	inputs: unknown | null
	payment_ref: string | null
	quarter: number | null
	status: Generated<string>
	updated_at: Generated<Timestamp>
	user_id: string
	year: number
}

export interface DB {
	account: Account
	chart_of_accounts: ChartOfAccounts
	cor_documents: CorDocuments
	invites: Invites
	jwks: Jwks
	session: Session
	tax_filings: TaxFilings
	tax_obligations: TaxObligations
	tax_profiles: TaxProfiles
	transaction_categories: TransactionCategories
	transactions: Transactions
	user: User
	user_preferences: UserPreferences
	verification: Verification
}
